
import type { Vehicle, User } from './types';

export const MOCK_USERS: User[] = [
    { name: 'Mock Dealer', email: 'dealer@test.com', password: 'password', mobile: '555-123-4567', role: 'dealer', status: 'active' },
    { name: 'Mock Customer', email: 'customer@test.com', password: 'password', mobile: '555-987-6543', role: 'customer', status: 'active' },
    { name: 'Mock Admin', email: 'admin@test.com', password: 'password', mobile: '111-222-3333', role: 'admin', status: 'active' }
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 1,
    make: 'Tesla',
    variant: 'Model 3',
    year: 2023,
    price: 38000,
    mileage: 15000,
    images: [
        'https://picsum.photos/seed/tesla1/800/600',
        'https://picsum.photos/seed/tesla2/800/600',
        'https://picsum.photos/seed/tesla3/800/600',
        'https://picsum.photos/seed/tesla4/800/600',
    ],
    features: ['Autopilot', 'Premium Interior', 'Long Range', '15-inch Touchscreen', 'Glass Roof'],
    description: 'A sleek and powerful electric sedan with cutting-edge technology.',
    dealerEmail: 'dealer@test.com',
    engine: 'Dual Motor Electric',
    transmission: '1-Speed Automatic',
    fuelType: 'Electric',
    mpg: '131 MPGe combined',
    exteriorColor: 'Midnight Silver Metallic',
    interiorColor: 'Black',
    status: 'published',
    isFeatured: true,
  },
  {
    id: 2,
    make: 'Ford',
    variant: 'Mustang Mach-E',
    year: 2022,
    price: 45000,
    mileage: 22000,
    images: [
        'https://picsum.photos/seed/ford1/800/600',
        'https://picsum.photos/seed/ford2/800/600',
        'https://picsum.photos/seed/ford3/800/600',
        'https://picsum.photos/seed/ford4/800/600',
    ],
    features: ['Extended Range Battery', 'GT Performance', 'Panoramic Roof', 'B&O Sound System'],
    description: 'Experience the thrill of electric performance in this iconic SUV.',
    dealerEmail: 'dealer@test.com',
    engine: 'Electric Motor',
    transmission: '1-Speed Automatic',
    fuelType: 'Electric',
    mpg: '90 MPGe combined',
    exteriorColor: 'Rapid Red Metallic',
    interiorColor: 'Black Onyx',
    status: 'published',
    isFeatured: false,
  },
  {
    id: 3,
    make: 'Rivian',
    variant: 'R1T',
    year: 2023,
    price: 75000,
    mileage: 8000,
    images: [
        'https://picsum.photos/seed/rivian1/800/600',
        'https://picsum.photos/seed/rivian2/800/600',
        'https://picsum.photos/seed/rivian3/800/600',
        'https://picsum.photos/seed/rivian4/800/600',
    ],
    features: ['Quad-Motor AWD', 'Adventure Package', 'Camp Kitchen', 'Reinforced Underbody Shield'],
    description: 'The ultimate electric adventure vehicle, ready for any terrain.',
    dealerEmail: 'dealer@test.com',
    engine: 'Quad-Motor Electric',
    transmission: '1-Speed Automatic',
    fuelType: 'Electric',
    mpg: '70 MPGe combined',
    exteriorColor: 'Launch Green',
    interiorColor: 'Forest Edge',
    status: 'published',
    isFeatured: false,
  },
  {
    id: 4,
    make: 'Porsche',
    variant: 'Taycan',
    year: 2023,
    price: 95000,
    mileage: 5000,
    images: [
        'https://picsum.photos/seed/porsche1/800/600',
        'https://picsum.photos/seed/porsche2/800/600',
        'https://picsum.photos/seed/porsche3/800/600',
        'https://picsum.photos/seed/porsche4/800/600',
    ],
    features: ['Performance Battery Plus', 'Sport Chrono Package', 'Bose Surround Sound', 'Adaptive Air Suspension'],
    description: 'Unmistakable Porsche performance, electrified. A true sports car soul.',
    dealerEmail: 'dealer@test.com',
    engine: 'Permanent Magnet Synchronous Motors',
    transmission: '2-Speed Automatic',
    fuelType: 'Electric',
    mpg: '79 MPGe combined',
    exteriorColor: 'Jet Black Metallic',
    interiorColor: 'Bordeaux Red',
    status: 'published',
    isFeatured: false,
  },
  {
    id: 5,
    make: 'Hyundai',
    variant: 'Ioniq 5',
    year: 2022,
    price: 42000,
    mileage: 18000,
    images: [
        'https://picsum.photos/seed/hyundai1/800/600',
        'https://picsum.photos/seed/hyundai2/800/600',
        'https://picsum.photos/seed/hyundai3/800/600',
        'https://picsum.photos/seed/hyundai4/800/600',
    ],
    features: ['Ultra-fast charging', 'Spacious Interior', 'Distinctive retro-futuristic design', 'Heads-Up Display'],
    description: 'A groundbreaking EV that combines innovative design with practical features.',
    dealerEmail: 'dealer@test.com',
    engine: 'Electric Motor',
    transmission: '1-Speed Automatic',
    fuelType: 'Electric',
    mpg: '114 MPGe combined',
    exteriorColor: 'Cyber Gray',
    interiorColor: 'Gray 2-Tone',
    status: 'published',
    isFeatured: false,
  },
  {
    id: 6,
    make: 'BMW',
    variant: 'i4',
    year: 2024,
    price: 58000,
    mileage: 3000,
    images: [
        'https://picsum.photos/seed/bmw1/800/600',
        'https://picsum.photos/seed/bmw2/800/600',
        'https://picsum.photos/seed/bmw3/800/600',
        'https://picsum.photos/seed/bmw4/800/600',
    ],
    features: ['M Sport Package', 'Harman Kardon Audio', 'Curved Display', 'Iconic Sounds Electric'],
    description: 'The ultimate electric driving machine, delivering exhilarating performance and luxury.',
    dealerEmail: 'dealer@test.com',
    engine: 'AC Synchronous Electric Motor',
    transmission: '1-Speed Automatic',
    fuelType: 'Electric',
    mpg: '109 MPGe combined',
    exteriorColor: 'Alpine White',
    interiorColor: 'Tacora Red',
    status: 'published',
    isFeatured: false,
  }
];