
import type { Vehicle, User } from './types';

// Helper to generate past dates
const daysAgo = (days: number): string => {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date.toISOString();
};

export const MOCK_USERS: User[] = [
    { name: 'Mock Seller', email: 'seller@test.com', password: 'password', mobile: '555-123-4567', role: 'seller', status: 'active', createdAt: daysAgo(30), dealershipName: 'Prestige Motors', bio: 'Specializing in luxury and performance electric vehicles since 2020.', logoUrl: 'https://i.pravatar.cc/100?u=seller' },
    { name: 'Mock Customer', email: 'customer@test.com', password: 'password', mobile: '555-987-6543', role: 'customer', status: 'active', createdAt: daysAgo(15) },
    { name: 'Mock Admin', email: 'admin@test.com', password: 'password', mobile: '111-222-3333', role: 'admin', status: 'active', createdAt: daysAgo(100) },
    { name: 'Jane Doe', email: 'jane.doe@customer.com', password: 'password', mobile: '555-111-2222', role: 'customer', status: 'active', createdAt: daysAgo(5) },
    { name: 'John Smith', email: 'john.smith@seller.com', password: 'password', mobile: '555-333-4444', role: 'seller', status: 'inactive', createdAt: daysAgo(60) },

];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 1,
    make: 'Tata',
    model: 'Nexon EV',
    year: 2023,
    price: 1650000,
    mileage: 15000,
    images: [
        'https://picsum.photos/seed/nexon1/800/600',
        'https://picsum.photos/seed/nexon2/800/600',
        'https://picsum.photos/seed/nexon3/800/600',
    ],
    features: ['Sunroof', 'Touchscreen Infotainment', 'Automatic Climate Control', 'Ziptron Technology'],
    description: 'A stylish and powerful compact electric SUV, perfect for city driving and weekend getaways.',
    sellerEmail: 'seller@test.com',
    engine: 'Permanent Magnet Synchronous Motor',
    transmission: 'Automatic',
    fuelType: 'Electric',
    fuelEfficiency: '325 km range',
    exteriorColor: 'Signature Teal Blue',
    interiorColor: 'Tri-arrow theme',
    status: 'published',
    isFeatured: true,
    views: 1850,
    inquiriesCount: 22,
    isFlagged: false,
  },
  {
    id: 2,
    make: 'Hyundai',
    model: 'Creta',
    year: 2022,
    price: 1400000,
    mileage: 28000,
    images: [
        'https://picsum.photos/seed/creta1/800/600',
        'https://picsum.photos/seed/creta2/800/600',
        'https://picsum.photos/seed/creta3/800/600',
    ],
    features: ['Panoramic Sunroof', 'Bose Premium Sound System', 'Ventilated Front Seats', 'BlueLink Connectivity'],
    description: 'The undisputed king of SUVs, offering a premium experience with robust performance.',
    sellerEmail: 'seller@test.com',
    engine: '1.5L MPi Petrol',
    transmission: 'CVT',
    fuelType: 'Petrol',
    fuelEfficiency: '17 KMPL',
    exteriorColor: 'Phantom Black',
    interiorColor: 'Black and Greige',
    status: 'published',
    isFeatured: false,
    views: 2200,
    inquiriesCount: 18,
    isFlagged: false,
  },
  {
    id: 3,
    make: 'Maruti Suzuki',
    model: 'Swift',
    year: 2023,
    price: 850000,
    mileage: 9000,
    images: [
        'https://picsum.photos/seed/swift1/800/600',
        'https://picsum.photos/seed/swift2/800/600',
    ],
    features: ['Cruise Control', 'SmartPlay Studio', 'Push Start-Stop Button', 'Sporty Alloy Wheels'],
    description: 'India\'s favorite hatchback, known for its peppy performance and excellent fuel efficiency.',
    sellerEmail: 'seller@test.com',
    engine: '1.2L DualJet Petrol',
    transmission: 'AGS (Automatic)',
    fuelType: 'Petrol',
    fuelEfficiency: '22.5 KMPL',
    exteriorColor: 'Solid Fire Red',
    interiorColor: 'Black',
    status: 'published',
    isFeatured: false,
    views: 1100,
    inquiriesCount: 15,
    isFlagged: true,
  },
  {
    id: 4,
    make: 'Mahindra',
    model: 'XUV700',
    year: 2022,
    price: 2200000,
    mileage: 21000,
    images: [
        'https://picsum.photos/seed/xuv1/800/600',
        'https://picsum.photos/seed/xuv2/800/600',
        'https://picsum.photos/seed/xuv3/800/600',
    ],
    features: ['ADAS', 'Dual HD Superscreen', 'Skyroof', 'Sony 3D Sound System'],
    description: 'A technologically advanced and powerful SUV built to thrill.',
    sellerEmail: 'john.smith@seller.com',
    engine: '2.0L Turbo Petrol',
    transmission: '6-Speed Automatic',
    fuelType: 'Petrol',
    fuelEfficiency: '15 KMPL',
    exteriorColor: 'Midnight Black',
    interiorColor: 'Plush Leatherette',
    status: 'published',
    isFeatured: false,
    views: 1950,
    inquiriesCount: 25,
    isFlagged: false,
  },
  {
    id: 5,
    make: 'Kia',
    model: 'Seltos',
    year: 2023,
    price: 1550000,
    mileage: 12000,
    images: [
        'https://picsum.photos/seed/seltos1/800/600',
        'https://picsum.photos/seed/seltos2/800/600',
    ],
    features: ['10.25-inch Touchscreen', 'Air Purifier', 'Heads-Up Display', 'Ambient Lighting'],
    description: 'A feature-packed SUV with a bold design that turns heads.',
    sellerEmail: 'john.smith@seller.com',
    engine: '1.5L CRDi VGT Diesel',
    transmission: '6-Speed Automatic',
    fuelType: 'Diesel',
    fuelEfficiency: '18 KMPL',
    exteriorColor: 'Intelligency Blue',
    interiorColor: 'Beige and Black',
    status: 'published',
    isFeatured: false,
    views: 1650,
    inquiriesCount: 11,
    isFlagged: false,
  },
  {
    id: 6,
    make: 'Honda',
    model: 'City',
    year: 2024,
    price: 1300000,
    mileage: 5000,
    images: [
        'https://picsum.photos/seed/city1/800/600',
        'https://picsum.photos/seed/city2/800/600',
        'https://picsum.photos/seed/city3/800/600',
    ],
    features: ['LaneWatch Camera', 'Full LED Headlamps', 'Electric Sunroof', '8-speaker sound system'],
    description: 'The quintessential sedan that combines luxury, comfort, and a refined driving experience.',
    sellerEmail: 'seller@test.com',
    engine: '1.5L i-VTEC Petrol',
    transmission: 'CVT',
    fuelType: 'Petrol',
    fuelEfficiency: '18.4 KMPL',
    exteriorColor: 'Golden Brown Metallic',
    interiorColor: 'Premium Beige',
    status: 'published',
    isFeatured: true,
    views: 980,
    inquiriesCount: 9,
    isFlagged: false,
  },
   {
    id: 7,
    make: 'Toyota',
    model: 'Fortuner',
    year: 2021,
    price: 3500000,
    mileage: 45000,
    images: [
        'https://picsum.photos/seed/fortuner1/800/600',
        'https://picsum.photos/seed/fortuner2/800/600',
    ],
    features: ['4x4 Capability', 'Leather Seats', 'JBL Speakers', 'Ventilated Seats'],
    description: 'The legendary SUV known for its commanding road presence and unbeatable reliability.',
    sellerEmail: 'seller@test.com',
    engine: '2.8L Diesel',
    transmission: '6-Speed Automatic',
    fuelType: 'Diesel',
    fuelEfficiency: '10 KMPL',
    exteriorColor: 'Sparkling Black Crystal Shine',
    interiorColor: 'Chamois',
    status: 'sold',
    isFeatured: false,
    views: 3500,
    inquiriesCount: 40,
    isFlagged: false,
  }
];